name: office_farm
pcd_map_file: office250619.pcd
pcd_viz_map_file: office250619.pcd
sectors:
- lane_id: 1
  height_id: 1
  horizon_id: 1
  required_viewpoint: right
  global_height: 1.2
  global_gv_pose:
  - 1
  - 2
  - 3
  depth_to_plants: 0.6

- lane_id: 1
  height_id: 2
  horizon_id: 1
  required_viewpoint: right
  global_height: 1.2
  global_gv_pose:
  - 1
  - 2
  - 3
  depth_to_plants: 0.6

- lane_id: 1
  height_id: 1
  horizon_id: 2
  required_viewpoint: right
  global_height: 1.2
  global_gv_pose:
  - 1
  - 2
  - 3
  depth_to_plants: 0.6




lanes:
- lane_id: 1
  lane_home:
  - -10
  - 2
  - 3
  lane_end:
  - 20
  - 2
  - 3
- lane_id: 1
  lane_home:
  - -10
  - 2
  - 3
  lane_end:
  - 20
  - 2
  - 3
