schedule_keys: # simple is always supported
  - only_left
  - only_right

only_left:
  # - l2h1h1rlf0
  # - l2h1h2rlf0
  # - l2h1h3rlf0
  # - l2h1h3rlf1
  # - l2h2h3rlf1
  # - l2h2h2rlf1
  # - l2h2h1rlf1

  - l2h1h3rlf0
  - l2h1h4rlf0
  - l2h2h4rlf0
  # - l2h1h4rlf1
  # - l2h1h3rlf1


only_right:
  # - l1h1h1rrf0
  # - l1h1h1rrf1


  - l1h1h3rrf0
  - l1h1h4rrf0
  - l1h2h4rrf0
  # - l1h1h5rrf0
  # - l1h1h5rrf1
  # - l1h1h4rrf1
  # - l1h1h3rrf1
